### ISSUE TITLE
colorama module not found on macOS 12 when using build.py

### ISSUE THREAD

**Issue by jaustin** [lancaster-university/codal-bootstrap#3]
using d5cd62c426ae85b2

```bash
jonny@machine codalproject % ./build.py 
Traceback (most recent call last):
  File "./build.py", line 33, in <module>
    from colorama import Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'
jonny@machine codalproject % 
```

on my machine, I could resolve this with 
`python3 -m pip install colorama`

**Comment by JohnVidler** [comment]
This should now be fixed as of 795f3cf49eab589abe416af2f8799ff75dc3db5c and f42109830382bd835f7ef046ff9bc5e1656e3e82

`Colorama` is now an optional dependency of Log.py, which will either A: use it if present, or B: just plain print text otherwise.

Users can therefore enable coloured output via `pip install colorama`
